In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [33]:
import pandas as pd
import math

In [4]:
dlc_output = pd.read_hdf('/Volumes/My_Passport/dlc_analysis/behavcamvideos/GRIN033_H14_M34_S32_01162020/dlc_output/behavCam05DLC_resnet50_Open_Field_v2Jan27shuffle1_150000.h5')

In [5]:
dlc_output.head()

scorer    DLC_resnet50_Open_Field_v2Jan27shuffle1_150000             \
bodyparts                                       ear_left
coords                                                 x          y
0                                             182.459595  64.162971
1                                             182.253250  63.902737
2                                             183.161713  63.787975
3                                             183.351120  64.231689
4                                             183.500870  64.538139

scorer                                                                         \
bodyparts              ear_right                         tail_base
coords    likelihood           x          y likelihood           x          y
0                1.0  175.690704  81.688751        1.0  135.587189  65.170486
1                1.0  175.381180  81.466217        1.0  135.700241  64.774269
2                1.0  175.693863  81.727692        1.0  135.493988  64.869102
3                1.0  175.139145  81.894554        1.0  135.557678  64.775795
4                1.0  174.939819  82.099571        1.0  135.829498  64.716202

scorer
bodyparts            miniscope_light
coords    likelihood               x          y likelihood
0                1.0      202.043701  78.638710        1.0
1                1.0      202.721512  78.175308        1.0
2                1.0      203.261276  78.705528        1.0
3                1.0      204.286987  80.260117        1.0
4                1.0      204.174301  80.721535        1.0

In [9]:
#dlc_output.diff()

In [38]:
coordinates_delta_df = pd.concat([dlc_output[df_columns[0][0]][body_part][['x', 'y']] for body_part in list(set([df_columns[item][1] for item in range(len(df_columns))]))], 
          keys=list(set([df_columns[item][1] for item in range(len(df_columns))])), axis=1).diff()

In [39]:
coordinates_delta_df.head()

        ear_left           miniscope_light           tail_base            \
coords         x         y               x         y         x         y
0            NaN       NaN             NaN       NaN       NaN       NaN
1      -0.206345 -0.260235        0.677811 -0.463402  0.113052 -0.396217
2       0.908463 -0.114761        0.539764  0.530220 -0.206253  0.094833
3       0.189407  0.443714        1.025711  1.554588  0.063690 -0.093307
4       0.149750  0.306450       -0.112686  0.461418  0.271820 -0.059593

       ear_right
coords         x         y
0            NaN       NaN
1      -0.309525 -0.222534
2       0.312683  0.261475
3      -0.554718  0.166862
4      -0.199326  0.205017

In [54]:
coordinates_delta_df['ear_left']['x'].values[1]+coordinates_delta_df['ear_left']['x'].values[1]

-0.2063446044921875

In [34]:
def velocity(x_diff, y_diff):
    v_t = math.sqrt(x_diff**2+y_diff**2)
    return(v_t)

In [53]:
velocity(coordinates_delta_df['ear_left']['x'].values[1],coordinates_delta_df['ear_left']['y'].values[1])

ValueError: math domain error

In [7]:
print(df_columns[0][1])
dlc_output[df_columns[0][0]][df_columns[0][1]]

ear_left

coords           x           y  likelihood
0       182.459595   64.162971         1.0
1       182.253250   63.902737         1.0
2       183.161713   63.787975         1.0
3       183.351120   64.231689         1.0
4       183.500870   64.538139         1.0
5       184.274597   65.008217         1.0
6       184.907181   64.904823         1.0
7       185.834366   64.617752         1.0
8       186.967407   64.249023         1.0
9       187.870117   63.711727         1.0
10      188.726730   64.144760         1.0
11      190.222733   65.488998         1.0
12      190.341034   65.364693         1.0
13      190.384583   65.578957         1.0
14      191.312805   65.740868         1.0
15      191.989151   65.632256         1.0
16      193.683731   65.864182         1.0
17      194.833664   65.576553         1.0
18      194.915909   66.608734         1.0
19      194.678314   67.131332         1.0
20      193.798187   66.588554         1.0
21      192.976044   66.079887         1.0
22      192.397659   65.301521         1.0
23      191.846359   64.740707         1.0
24      190.913330   64.962334         1.0
25      190.543549   65.787216         1.0
26      190.296997   66.375473         1.0
27      190.326523   66.616440         1.0
28      189.961746   66.360054         1.0
29      189.378036   66.136337         1.0
..             ...         ...         ...
970     371.157928  258.927917         1.0
971     371.410522  259.295105         1.0
972     371.547272  259.231354         1.0
973     372.011353  258.802338         1.0
974     370.922058  258.475189         1.0
975     370.784729  258.303040         1.0
976     370.738678  258.864716         1.0
977     371.505402  259.037628         1.0
978     371.360901  259.247528         1.0
979     371.600555  259.676361         1.0
980     372.256500  260.436127         1.0
981     373.814667  259.008453         1.0
982     375.038025  256.244202         1.0
983     375.660156  253.771866         1.0
984     375.952179  252.962753         1.0
985     376.096985  252.875534         1.0
986     376.078125  252.929031         1.0
987     375.631897  252.200729         1.0
988     375.029175  252.052917         1.0
989     374.902283  252.167236         1.0
990     374.984650  252.356339         1.0
991     375.175476  252.337341         1.0
992     374.727570  251.338608         1.0
993     374.041840  250.957321         1.0
994     374.167145  251.677124         1.0
995     373.366302  252.167007         1.0
996     372.876801  252.326599         1.0
997     373.057007  253.399963         1.0
998     373.194427  255.464996         1.0
999     373.341827  256.752441         1.0

[1000 rows x 3 columns]

In [27]:
#create body part delta data frame 
body_part_deltas = []
for body_part in range:    
    body_part_delta = [dlc_output.iloc[frame+1,1]-dlc_output.iloc[frame,1] for frame in range (0, 999)]

TypeError: 'type' object is not iterable